/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.frmprincipal;

/**
 *
 * @author luiz
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
public FrmPrincipal() {
    initComponents();

    // Configura o cursor de "mão" para todas as labels
    GerenciarCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    GerenciarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    MovimentarEst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Relatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    // Adiciona efeitos de hover e clique
    addButtonEffect(GerenciarCat, "Gerenciar Categorias");
    addButtonEffect(GerenciarProd, "Gerenciar Produtos");
    addButtonEffect(MovimentarEst, "Movimentar Estoque");
    addButtonEffect(Relatorios, "Relatórios");
}

// 🔹 Método genérico que aplica efeitos em qualquer JLabel
private void addButtonEffect(javax.swing.JLabel label, String acao) {
    label.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            // Leve aumento no hover
            label.setSize(label.getWidth() + 2, label.getHeight() + 2);
            label.setLocation(label.getX() - 1, label.getY() - 1);
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            // Volta ao tamanho normal
            label.setSize(label.getWidth() - 2, label.getHeight() - 2);
            label.setLocation(label.getX() + 1, label.getY() + 1);
            label.setOpaque(false);
        }

        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            // Efeito de clique: "aperta" o botão
            label.setSize(label.getWidth() - 2, label.getHeight() - 2);
            label.setLocation(label.getX() + 1, label.getY() + 1);
        }

        @Override
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            // Volta ao tamanho original
            label.setSize(label.getWidth() + 2, label.getHeight() + 2);
            label.setLocation(label.getX() - 1, label.getY() - 1);

            // Aqui entra a ação do clique:
            System.out.println("Botão clicado: " + acao);

            // Exemplo: abrir outra janela (substitua conforme seu projeto)
            /*
            if (acao.equals("Gerenciar Categorias")) {
                new FrmGerenciaCategoria().setVisible(true);
            }
            */
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        PainelInicio = new javax.swing.JPanel();
        GuiaGerenciador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GerenciarCat = new javax.swing.JLabel();
        GerenciarProd = new javax.swing.JLabel();
        MovimentarEst = new javax.swing.JLabel();
        Relatorios = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelInicio.setBackground(new java.awt.Color(204, 204, 204));

        GuiaGerenciador.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciador");

        GerenciarCat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GerenciarCat.setForeground(new java.awt.Color(255, 255, 255));
        GerenciarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconBarra.png"))); // NOI18N
        GerenciarCat.setText("Gerenciar Categorias");

        GerenciarProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GerenciarProd.setForeground(new java.awt.Color(255, 255, 255));
        GerenciarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconBarra.png"))); // NOI18N
        GerenciarProd.setText("Gerenciar Produtos");

        MovimentarEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MovimentarEst.setForeground(new java.awt.Color(255, 255, 255));
        MovimentarEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconConfig.png"))); // NOI18N
        MovimentarEst.setText("Movimentar Estoque");

        Relatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Relatorios.setForeground(new java.awt.Color(255, 255, 255));
        Relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconRelatorio.png"))); // NOI18N
        Relatorios.setText("Relatórios");

        javax.swing.GroupLayout GuiaGerenciadorLayout = new javax.swing.GroupLayout(GuiaGerenciador);
        GuiaGerenciador.setLayout(GuiaGerenciadorLayout);
        GuiaGerenciadorLayout.setHorizontalGroup(
            GuiaGerenciadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                .addGroup(GuiaGerenciadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(GerenciarCat))
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(GerenciarProd))
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(MovimentarEst))
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Relatorios))
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        GuiaGerenciadorLayout.setVerticalGroup(
            GuiaGerenciadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(GerenciarCat)
                .addGap(18, 18, 18)
                .addComponent(GerenciarProd)
                .addGap(18, 18, 18)
                .addComponent(MovimentarEst)
                .addGap(18, 18, 18)
                .addComponent(Relatorios)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PainelPrincipal.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout PainelInicioLayout = new javax.swing.GroupLayout(PainelInicio);
        PainelInicio.setLayout(PainelInicioLayout);
        PainelInicioLayout.setHorizontalGroup(
            PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInicioLayout.createSequentialGroup()
                .addComponent(GuiaGerenciador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PainelInicioLayout.setVerticalGroup(
            PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GuiaGerenciador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GerenciarCat;
    private javax.swing.JLabel GerenciarProd;
    private javax.swing.JPanel GuiaGerenciador;
    private javax.swing.JLabel MovimentarEst;
    private javax.swing.JPanel PainelInicio;
    private javax.swing.JLabel Relatorios;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
