/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.frmprincipal;

import view.frmcategoria.FrmCategoria;
import view.frmproduto.FrmGerenciarProdutos;


/**
 *
 * @author luiz
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        // Configura o cursor de "mão" para todas as labels
        GerenciarCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GerenciarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MovimentarEst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Relatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Adiciona efeitos de hover e clique
        addButtonEffect(GerenciarCat, "Gerenciar Categorias");
        addButtonEffect(GerenciarProd, "Gerenciar Produtos");
        addButtonEffect(MovimentarEst, "Movimentar Estoque");
        addButtonEffect(Relatorios, "Relatórios");
    }

// 🔹 Método genérico que aplica efeitos em qualquer JLabel
    private void addButtonEffect(javax.swing.JLabel label, String acao) {
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Leve aumento no hover
                label.setSize(label.getWidth() + 2, label.getHeight() + 2);
                label.setLocation(label.getX() - 1, label.getY() - 1);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Volta ao tamanho normal
                label.setSize(label.getWidth() - 2, label.getHeight() - 2);
                label.setLocation(label.getX() + 1, label.getY() + 1);
                label.setOpaque(false);
            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                // Efeito de clique: "aperta" o botão
                label.setSize(label.getWidth() - 2, label.getHeight() - 2);
                label.setLocation(label.getX() + 1, label.getY() + 1);
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                // Volta ao tamanho original
                label.setSize(label.getWidth() + 2, label.getHeight() + 2);
                label.setLocation(label.getX() - 1, label.getY() - 1);

                // Aqui entra a ação do clique:
                System.out.println("Botão clicado: " + acao);

                // Exemplo: abrir outra janela (substitua conforme seu projeto)
                /*
            if (acao.equals("Gerenciar Categorias")) {
                new FrmGerenciaCategoria().setVisible(true);
            }
                 */
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        PainelInicio = new javax.swing.JPanel();
        GuiaGerenciador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GerenciarCat = new javax.swing.JLabel();
        GerenciarProd = new javax.swing.JLabel();
        MovimentarEst = new javax.swing.JLabel();
        Relatorios = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelInicio.setBackground(new java.awt.Color(204, 204, 204));

        GuiaGerenciador.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");

        GerenciarCat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GerenciarCat.setForeground(new java.awt.Color(255, 255, 255));
        GerenciarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconBarra.png"))); // NOI18N
        GerenciarCat.setText("Gerenciar Categorias");
        GerenciarCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GerenciarCatMouseClicked(evt);
            }
        });

        GerenciarProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GerenciarProd.setForeground(new java.awt.Color(255, 255, 255));
        GerenciarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconBarra.png"))); // NOI18N
        GerenciarProd.setText("Gerenciar Produtos");
        GerenciarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GerenciarProdMouseClicked(evt);
            }
        });

        MovimentarEst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MovimentarEst.setForeground(new java.awt.Color(255, 255, 255));
        MovimentarEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconConfig.png"))); // NOI18N
        MovimentarEst.setText("Movimentar Estoque");

        Relatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Relatorios.setForeground(new java.awt.Color(255, 255, 255));
        Relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconRelatorio.png"))); // NOI18N
        Relatorios.setText("Relatórios");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Sistema de Gerenciamento de Estoque");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("© 2025 A3 Sistemas Distribuidos. Luiz, Mario e Fabricio. Todos os direitos reservados.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(222, 222, 222)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout GuiaGerenciadorLayout = new javax.swing.GroupLayout(GuiaGerenciador);
        GuiaGerenciador.setLayout(GuiaGerenciadorLayout);
        GuiaGerenciadorLayout.setHorizontalGroup(
            GuiaGerenciadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                .addGroup(GuiaGerenciadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(GerenciarCat))
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(GerenciarProd))
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(MovimentarEst))
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Relatorios))
                    .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        GuiaGerenciadorLayout.setVerticalGroup(
            GuiaGerenciadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(GerenciarCat)
                .addGap(18, 18, 18)
                .addComponent(GerenciarProd)
                .addGap(18, 18, 18)
                .addComponent(MovimentarEst)
                .addGap(18, 18, 18)
                .addComponent(Relatorios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PainelInicioLayout = new javax.swing.GroupLayout(PainelInicio);
        PainelInicio.setLayout(PainelInicioLayout);
        PainelInicioLayout.setHorizontalGroup(
            PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInicioLayout.createSequentialGroup()
                .addComponent(GuiaGerenciador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelInicioLayout.setVerticalGroup(
            PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GuiaGerenciador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GerenciarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerenciarProdMouseClicked
        try {
            FrmGerenciarProdutos frmGerenciarProdutos = new FrmGerenciarProdutos();
            frmGerenciarProdutos.setVisible(true);
            frmGerenciarProdutos.setLocationRelativeTo(this); // centraliza em relação à janela atual
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao abrir a tela de Categorias: " + e.getMessage());
        }
    }//GEN-LAST:event_GerenciarProdMouseClicked

    private void GerenciarCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerenciarCatMouseClicked
        try {
            FrmCategoria frmCategoria = new FrmCategoria();
            frmCategoria.setVisible(true);
            frmCategoria.setLocationRelativeTo(this); // centraliza em relação à janela atual
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao abrir a tela de Categorias: " + e.getMessage());
        }
    }//GEN-LAST:event_GerenciarCatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GerenciarCat;
    private javax.swing.JLabel GerenciarProd;
    private javax.swing.JPanel GuiaGerenciador;
    private javax.swing.JLabel MovimentarEst;
    private javax.swing.JPanel PainelInicio;
    private javax.swing.JLabel Relatorios;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
