package view.frmcategoria;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Categoria;
import client.Cliente;
import model.Categoria;
import java.util.List;
import javax.swing.JTable;

public class FrmCategoria extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCategoria.class.getName());

    public FrmCategoria() {
        initComponents();
        carregarCategorias();
        // 🔹 Aqui você adiciona os valores do enum ao ComboBox
        JCBEmbalagem2.removeAllItems(); // limpa se tiver algo
        for (model.EmbalagemProduto e : model.EmbalagemProduto.values()) {
            JCBEmbalagem2.addItem(e.name()); // adiciona PLASTICO, VIDRO, PAPELAO
        }

        // (opcional) Se quiser selecionar o primeiro item automaticamente
        if (JCBEmbalagem2.getItemCount() > 0) {
            JCBEmbalagem2.setSelectedIndex(0);
        }

        // 🔹 Faça o mesmo com o combo de tamanhos, se quiser
        JCBTamanho1.removeAllItems();
        for (model.TamanhoProduto t : model.TamanhoProduto.values()) {
            JCBTamanho1.addItem(t.name());
        }
    }

    private void carregarCategorias() {
        try {
            client.Cliente cliente = new client.Cliente();
            cliente.conectar("localhost", 1234);
            cliente.enviarComando("LISTAR_CATEGORIAS");
            Object resposta = cliente.receberObjeto();
            cliente.close();

            DefaultTableModel model = (DefaultTableModel) TabelaCategorias.getModel();
            model.setRowCount(0);

            if (resposta instanceof java.util.List<?>) {
                java.util.List<model.Categoria> lista = (java.util.List<model.Categoria>) resposta;
                for (model.Categoria c : lista) {
                    model.addRow(new Object[]{
                        c.getId(),
                        c.getNome(),
                        c.getEmbalagem(),
                        c.getTamanho()
                    });
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao carregar categorias:\n" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelInicio = new javax.swing.JPanel();
        JCBEmbalagem = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        JCBTamanho = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        JTFNomeCadastro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        GuiaGerenciador = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCategorias = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        JCBTamanho1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnApagar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        JCBEmbalagem2 = new javax.swing.JComboBox<>();
        JTFNomeCadastro1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelInicio.setBackground(new java.awt.Color(204, 204, 204));
        PainelInicio.setForeground(new java.awt.Color(0, 0, 0));

        JCBEmbalagem.setBackground(new java.awt.Color(255, 255, 255));
        JCBEmbalagem.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        JCBEmbalagem.setForeground(new java.awt.Color(0, 0, 0));
        JCBEmbalagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lata", "Vidro", "Plástico" }));

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Embalagem");

        JCBTamanho.setBackground(new java.awt.Color(255, 255, 255));
        JCBTamanho.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        JCBTamanho.setForeground(new java.awt.Color(0, 0, 0));
        JCBTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno", "Médio", "Grande" }));
        JCBTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBTamanhoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tamanho");

        JTFNomeCadastro.setBackground(new java.awt.Color(255, 255, 255));
        JTFNomeCadastro.setForeground(new java.awt.Color(0, 0, 0));
        JTFNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeCadastroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nome");

        GuiaGerenciador.setBackground(new java.awt.Color(0, 0, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gerenciamento de Categorias");

        javax.swing.GroupLayout GuiaGerenciadorLayout = new javax.swing.GroupLayout(GuiaGerenciador);
        GuiaGerenciador.setLayout(GuiaGerenciadorLayout);
        GuiaGerenciadorLayout.setHorizontalGroup(
            GuiaGerenciadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiaGerenciadorLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GuiaGerenciadorLayout.setVerticalGroup(
            GuiaGerenciadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        TabelaCategorias.setBackground(new java.awt.Color(255, 255, 255));
        TabelaCategorias.setForeground(new java.awt.Color(0, 0, 0));
        TabelaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Embalagem", "Tamanho"
            }
        ));
        TabelaCategorias.setToolTipText("");
        TabelaCategorias.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TabelaCategoriasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TabelaCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaCategorias);

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cadastrar Categoria");

        JCBTamanho1.setBackground(new java.awt.Color(255, 255, 255));
        JCBTamanho1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        JCBTamanho1.setForeground(new java.awt.Color(0, 0, 0));
        JCBTamanho1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno", "Médio", "Grande" }));
        JCBTamanho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBTamanho1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Embalagem");

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Tamanho");

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Categoria");

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Gerenciar Categorias");

        btnApagar.setBackground(new java.awt.Color(0, 0, 51));
        btnApagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApagar.setForeground(new java.awt.Color(255, 255, 255));
        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(0, 0, 51));
        btnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(0, 0, 51));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        voltar.setBackground(new java.awt.Color(0, 0, 51));
        voltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        voltar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                voltarComponentMoved(evt);
            }
        });
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        JCBEmbalagem2.setBackground(new java.awt.Color(255, 255, 255));
        JCBEmbalagem2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        JCBEmbalagem2.setForeground(new java.awt.Color(0, 0, 0));
        JCBEmbalagem2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLASTICO", "VIDRO", "PAPELAO", "LATA" }));
        JCBEmbalagem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBEmbalagem2ActionPerformed(evt);
            }
        });

        JTFNomeCadastro1.setBackground(new java.awt.Color(255, 255, 255));
        JTFNomeCadastro1.setForeground(new java.awt.Color(0, 0, 0));
        JTFNomeCadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeCadastro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelInicioLayout = new javax.swing.GroupLayout(PainelInicio);
        PainelInicio.setLayout(PainelInicioLayout);
        PainelInicioLayout.setHorizontalGroup(
            PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GuiaGerenciador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(PainelInicioLayout.createSequentialGroup()
                .addGroup(PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelInicioLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel10))
                    .addGroup(PainelInicioLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelInicioLayout.createSequentialGroup()
                                .addGroup(PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JTFNomeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(JCBEmbalagem, 0, 242, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(116, 116, 116)
                .addGroup(PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelInicioLayout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBTamanho1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelInicioLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14))
                    .addComponent(JCBEmbalagem2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFNomeCadastro1))
                .addGap(58, 58, 58))
        );
        PainelInicioLayout.setVerticalGroup(
            PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInicioLayout.createSequentialGroup()
                .addComponent(GuiaGerenciador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelInicioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFNomeCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBTamanho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBEmbalagem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelInicioLayout.createSequentialGroup()
                        .addGroup(PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(JTFNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(PainelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagar)
                    .addComponent(btnAlterar)
                    .addComponent(btnCadastrar)
                    .addComponent(voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here
        // Fecha a janela atual e retorna ao menu principal
        this.dispose();
        // Se houver outra tela principal:
        // new MenuPrincipalView().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void voltarComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_voltarComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarComponentMoved

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_voltarMouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        try {
            String nome = JTFNomeCadastro.getText().trim();
            String embalagem = JCBEmbalagem.getSelectedItem().toString();
            String tamanho = JCBTamanho.getSelectedItem().toString();

            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o nome da categoria.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Categoria categoria = new Categoria();
            categoria.setNome(nome);
            categoria.setEmbalagem(model.EmbalagemProduto.valueOf(embalagem.toUpperCase()));
            categoria.setTamanho(model.TamanhoProduto.valueOf(tamanho.toUpperCase()));

            client.Cliente cliente = new client.Cliente();
            cliente.conectar("localhost", 1234);

            cliente.enviarComando("INSERIR_CATEGORIA");
            cliente.enviarObjeto(categoria);

            String resposta = cliente.receberMensagem();
            cliente.close();

            JOptionPane.showMessageDialog(this,
                    (resposta != null ? resposta : "Categoria cadastrada com sucesso!"),
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            JTFNomeCadastro.setText("");
            carregarCategorias();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao cadastrar categoria:\n" + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        int linha = TabelaCategorias.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria na tabela para alterar.");
            return;
        }

        int id = (int) TabelaCategorias.getValueAt(linha, 0);
        String nome = JTFNomeCadastro1.getText().trim();

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome da categoria.");
            return;
        }

        // 🔥 Aqui o pulo do gato:
        Object embObj = JCBEmbalagem2.getSelectedItem();
        Object tamObj = JCBTamanho1.getSelectedItem();

        model.EmbalagemProduto embalagem = null;
        model.TamanhoProduto tamanho = null;

        if (embObj instanceof model.EmbalagemProduto) {
            embalagem = (model.EmbalagemProduto) embObj;
        } else if (embObj instanceof String) {
            embalagem = model.EmbalagemProduto.valueOf(((String) embObj).toUpperCase());
        }

        if (tamObj instanceof model.TamanhoProduto) {
            tamanho = (model.TamanhoProduto) tamObj;
        } else if (tamObj instanceof String) {
            tamanho = model.TamanhoProduto.valueOf(((String) tamObj).toUpperCase());
        }

        // Monta o objeto categoria
        model.Categoria categoria = new model.Categoria();
        categoria.setId(id);
        categoria.setNome(nome);
        categoria.setEmbalagem(embalagem);
        categoria.setTamanho(tamanho);

        try {
            client.Cliente cliente = new client.Cliente();
            cliente.conectar("localhost", 1234);
            cliente.enviarComando("ATUALIZAR_CATEGORIA");
            cliente.enviarObjeto(categoria);

            String resposta = cliente.receberMensagem();
            cliente.close();

            JOptionPane.showMessageDialog(this,
                    resposta != null ? resposta : "Categoria alterada com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            carregarCategorias(); // Atualiza a tabela

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao alterar categoria:\n" + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        int linha = TabelaCategorias.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria na tabela para excluir.");
            return;
        }

        // Pega o ID e o nome diretamente da tabela
        int id = (int) TabelaCategorias.getValueAt(linha, 0); // coluna 0 = ID
        String nome = (String) TabelaCategorias.getValueAt(linha, 1); // coluna 1 = Nome

        int confirm = JOptionPane.showConfirmDialog(this,
                "Deseja realmente excluir a categoria \"" + nome + "\"?",
                "Confirmação", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // Conecta com o servidor
            client.Cliente cliente = new client.Cliente();
            cliente.conectar("localhost", 1234);

            // Envia comando de exclusão e ID
            cliente.enviarComando("EXCLUIR_CATEGORIA");
            cliente.enviarObjeto(id);

            // Recebe resposta do servidor
            String resposta = cliente.receberMensagem();
            cliente.close();

            JOptionPane.showMessageDialog(this,
                    resposta != null ? resposta : "Categoria excluída com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            carregarCategorias(); // Atualiza a tabela

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao excluir categoria:\n" + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void JCBTamanho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBTamanho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBTamanho1ActionPerformed

    private void TabelaCategoriasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabelaCategoriasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaCategoriasAncestorAdded

    private void JTFNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNomeCadastroActionPerformed

    private void JCBTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBTamanhoActionPerformed
        // Não implementado
    }//GEN-LAST:event_JCBTamanhoActionPerformed

    private void JTFNomeCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeCadastro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNomeCadastro1ActionPerformed

    private void JCBEmbalagem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBEmbalagem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBEmbalagem2ActionPerformed

    private void TabelaCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCategoriasMouseClicked
        // TODO add your handling code here:
        int selectedRow = TabelaCategorias.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        // Coluna 1 = Nome da categoria
        Object nomeObj = TabelaCategorias.getValueAt(selectedRow, 1);
        if (nomeObj != null) {
            JTFNomeCadastro1.setText(nomeObj.toString());
        }

        // Coluna 2 = Embalagem (Enum)
        Object embObj = TabelaCategorias.getValueAt(selectedRow, 2);
        if (embObj instanceof model.EmbalagemProduto emb) {
            JCBEmbalagem2.setSelectedItem(emb.name());
        } else if (embObj != null) {
            JCBEmbalagem2.setSelectedItem(embObj.toString());
        }

        // Coluna 3 = Tamanho (Enum)
        Object tamObj = TabelaCategorias.getValueAt(selectedRow, 3);
        if (tamObj instanceof model.TamanhoProduto tam) {
            JCBTamanho1.setSelectedItem(tam.name());
        } else if (tamObj != null) {
            JCBTamanho1.setSelectedItem(tamObj.toString());
        }
    }//GEN-LAST:event_TabelaCategoriasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCategoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GuiaGerenciador;
    private javax.swing.JComboBox<String> JCBEmbalagem;
    private javax.swing.JComboBox<String> JCBEmbalagem2;
    private javax.swing.JComboBox<String> JCBTamanho;
    private javax.swing.JComboBox<String> JCBTamanho1;
    private javax.swing.JTextField JTFNomeCadastro;
    private javax.swing.JTextField JTFNomeCadastro1;
    private javax.swing.JPanel PainelInicio;
    private javax.swing.JTable TabelaCategorias;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
